const ADD = 'ADD_CONTACT';
const REMOVE = 'REMOVE_CONTACT';
const FIND_CONTACT = 'FIND_CONTACT';
const ADD_REQUEST = 'ADD_REQUEST';
const ADD_SUCCESS = 'ADD_SUCCESS';
const ADD_ERROR = 'ADD_ERROR';
const GET_REQUEST = 'GET_REQUEST';
const GET_SUCCESS = 'GET_SUCCESS';
const GET_ERROR = 'GET_ERROR';
const REMOVE_REQUEST = 'REMOVE_REQUEST';
const REMOVE_SUCCESS = 'REMOVE_SUCCESS';
const REMOVE_ERROR = 'REMOVE_ERROR'

export default {
    ADD,
    REMOVE,
    FIND_CONTACT,
    ADD_REQUEST,
    ADD_SUCCESS,
    ADD_ERROR,
    GET_REQUEST,
    GET_SUCCESS,
    GET_ERROR,
    REMOVE_REQUEST,
    REMOVE_SUCCESS,
    REMOVE_ERROR
}